### ISSUE TITLE
laradrop is not a function

### ISSUE THREAD

**Issue by bikedel** [jasekz/laradrop#1]
hello I am getting this error after following the install instructions

laravel 5.2

**Comment by jasekz** [comment]
Hello,
Is it a JavaScript error or a Laravel/php error?  If you could provide a screenshot, that would be great.

Thanks,
Zig

**Comment by bikedel** [comment]
Hi Zig

Thank you very much for your reply. My problem was I was loading jquery twice..

Regards
Paul
