### ISSUE TITLE
Over Riding Laradrops Controller still calls Laradrops Controller

### ISSUE THREAD

**Issue by devingray** [jasekz/laradrop#13]
I have made a new controller like this 

```
<?php 

use Jasekz\Laradrop\Http\Controllers\LaradropController;
use Input, Auth;

class UserMediaController extends LaradropController {
    
    /**
     * Upload and store new file.
     *
     * @return JsonResponse
     */
    public function store()
    {
        try {
          
            if (! Request::hasFile('file')) {
                throw new Exception(trans('err.fileNotProvided'));
            }
            
            if( ! Request::file('file')->isValid()) {
                throw new Exception(trans('err.invalidFile'));
            }
            
            /*
             * move file to temp location
             */
            $fileExt = Input::file('file')->getClientOriginalExtension();
            $fileName = str_replace('.' . $fileExt, '', Input::file('file')->getClientOriginalName()) . '-' . date('Ymdhis');
            $mimeType = Request::file('file')->getMimeType();
            $tmpStorage = storage_path();
            $movedFileName = $fileName . '.' . $fileExt;
            $fileSize = Input::file('file')->getSize();

            if($fileSize > ( (int) config('laradrop.max_upload_size') * 1000000) ) {
                throw new Exception(trans('err.invalidFileSize'));
            }
            
            Request::file('file')->move($tmpStorage, $movedFileName);
            
            $disk = Storage::disk(config('laradrop.disk'));

            /*
             * create thumbnail if needed
             */
            $fileData['has_thumbnail'] = 0;
            if ($fileSize <= ( (int) config('laradrop.max_thumbnail_size') * 1000000) && in_array($fileExt, ['jpg', 'jpeg', 'png', 'gif'])) {

                $thumbDims = config('laradrop.thumb_dimensions');
                $img = Image::make($tmpStorage . '/' . $movedFileName);
                $img->resize($thumbDims['width'], $thumbDims['height']);
                $img->save($tmpStorage . '/_thumb_' . $movedFileName);

                // move thumbnail to final location
                $disk->put('_thumb_' . $movedFileName, fopen($tmpStorage . '/_thumb_' . $movedFileName, 'r+'));
                File::delete($tmpStorage . '/_thumb_' . $movedFileName);                
                $fileData['has_thumbnail'] = 1;
                
            } 

            /*
             * move uploaded file to final location
             */
            $disk->put($movedFileName, fopen($tmpStorage . '/' . $movedFileName, 'r+'));
            File::delete($tmpStorage . '/' . $movedFileName);
            
            /*
             * save in db
             */

            if (!Auth::user()->currentTeam()){
            $eitherTeamOrUser = \Auth::user()->finduser;
            }

            elseif(Auth::user()->currentTeam()){
                $eitherTeamOrUser = \Auth::user()->currentTeam()->findteam;
            }
            $fileData['findimage'] = 1;       
            $fileData['filename'] = $movedFileName;  
            $fileData['alias'] = Input::file('file')->getClientOriginalName();
            $fileData['public_resource_url'] = config('laradrop.disk_public_url') . '/' . $movedFileName;
            $fileData['type'] = $fileExt;
            if(Input::get('pid') > 0) {
                $fileData['parent_id'] = Input::get('pid');
            }
            $meta = $disk->getDriver()->getAdapter()->getMetaData($movedFileName);
            $meta['disk'] = config('laradrop.disk');
            $fileData['meta'] = json_encode($meta);
            $file = $this->file->create($fileData);
            
            /*
             * fire 'file uploaded' event
             */
            event(new FileWasUploaded([
                'file'     => $file,
                'postData' => Input::all()
            ]));
            
            return $file;
            
        } 

        catch (Exception $e) {
            
            // delete the file(s)
            if( isset($disk) && $disk) {
                $disk->delete($movedFileName);
                $disk->delete('_thumb_' . $movedFileName);
            }
            
            return $this->handleError($e);
        }
    }

    }
```

Basically, I am trying to override the store method to add a findimage column in the DB. I have altered the migration made the above controller. I cannot get Auth::user() it always returns null if I make it directly in the laradropController, So I am trying to override it to have that function available to me. 

```
 if (!Auth::user()->currentTeam()){
            $eitherTeamOrUser = \Auth::user()->finduser;
            }

            elseif(Auth::user()->currentTeam()){
                $eitherTeamOrUser = \Auth::user()->currentTeam()->findteam;
            }
            $fileData['findimage'] = 1;
```

But this does not overwrite the laradropsController. 

I have added these routes

```
//User Media Files 
Route::get('mediaIndex', 'UserMediaController@index');
Route::post('mediaStore', 'UserMediaController@store');
Route::post('mediaDestroy', 'UserMediaController@destroy');
Route::post('mediaMove', 'UserMediaController@move');
Route::post('mediaCreate', 'UserMediaController@create');
```

And instantiate the laradrops like this

```
<div class="laradrop"
              laradrop-file-source="/mediaIndex" 
              laradrop-upload-handler="/mediaStore"
              laradrop-file-delete-handler="/mediaDestroy"
              laradrop-file-move-handler="/mediaMove"
              laradrop-file-create-handler="/mediaCreate"
              laradrop-csrf-token="bVgziBueIHaJqYdIruMg5pW2tISSEFMs9Qc5K7AY">
          </div>
```

Any idea why it doesnt hit my new controller?

**Comment by jasekz** [comment]
Hey Devin,
Thanks for bringing this to my attention.  The reason that this wasn't working for you, was because of a bug in the javascript file.  This is now fixed, if you want to update your code.  Alternatively, you can use the event handler method below if you don't feel like doing an update.  With that being said, here is how you can accomplish your goal:

EVENT HANDLER (preferred - this keeps your code nicely decoupled)
1. In your app/Providers/EventServiceProvider.php file, add a listener:

```
protected $listen = [
  'Jasekz\Laradrop\Events\FileWasUploaded' => [
    'App\Handlers\Events\LaradropFileWasUploaded',
  ],
];
```


2. Generate the handler with:
`artisan handler:event 'App\Handlers\Events\LaradropFileWasUploaded' --event='Jasekz\Laradrop\Events\FileWasUploaded'`

3. In the newly generated handler file - app/Handlers/Events/LaradropFileWasUploaded.php, change:
`use App\Events\Jasekz\Laradrop\Events\FileWasUploaded` 
to 
`use Jasekz\Laradrop\Events\FileWasUploaded`

4. In the `handle()` function, you can now access the uploaded file object and perform your business logic as needed.  For example:

```
public function handle(FileWasUploaded $event) {
  $file = $event->data['file'];
  $file->findimage = 3;
  $file->update();
}
```

CONTROLLER OVERRIDE METHOD
1. Create the controller (as you have), but you can skip all the laradrop code and just add your business logic.  The parent returns a file object you can utilize.  For example:

```
public function store() {
  try {
    $file = parent::store();
    $file->findimage = 1;
    $file->update();
  } 
  catch (Exception $e) {
    return $this->handleError($e);
  }
}
```
2. Make sure your controller is name spaced correctly:
`namespace App\Http\Controllers;`
3. In your view, all you need is the upload handler.
```
<div class="laradrop"
    laradrop-upload-handler="/mediaStore"
    laradrop-csrf-token="{{ csrf_token() }}">
</div>
```

I didn't get into the Auth::user() functionality because that's outside of the scope, but you should be able to use it in the normal Laravel way.  Let me know if this helps and/or if the issue persists.

Thanks,
Zig

**Comment by devingray** [comment]
Hi Zig and thanks for the response. I tried both methods and they seem to not be working. I would prefer the controller override method, as I can then get it to work as I need it, but I am still not hitting my controller. 

I have this code below. My Goal is to assign findimage the users ID. So that I can collect only images assigned to that user. I do not want to use folders. Its one image per user. 

```
<div class="laradrop"
              laradrop-file-source="/mediaIndex" 
              laradrop-upload-handler="/mediaStore"
              laradrop-csrf-token="{{csrf_field()}}">
          </div>
```

This is where I instantiate my laradrop. 

and my routes

```
//User Media Files 
Route::get('mediaIndex', 'UserMediaController@index');
Route::post('mediaStore', 'UserMediaController@store');
```

But for some reason it is still not getting to that controller. I also want to crop and resize the image in the controller so over riding it would be my best option. 

But am at a loss as to why this is not happening. New controller below

```
<?php 

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Jasekz\Laradrop\Http\Controllers\LaradropController;
use Input, Auth;

class UserMediaController extends LaradropController {
    
    /**
     * Upload and store new file.
     *
     * @return JsonResponse
     */
    public function store()
    {

        if (!Auth::user()->currentTeam()){
            $eitherTeamOrUser = \Auth::user()->finduser;
        }

        elseif(Auth::user()->currentTeam()){
            $eitherTeamOrUser = \Auth::user()->currentTeam()->findteam;
        }

        try {
            $file = parent::store();
            $file->findimage = $eitherTeamOrUser;
            $file->update();
          } 
          catch (Exception $e) {
            return $this->handleError($e);
          }

    }
```

**Comment by devingray** [comment]
Oh yes and this command `php artisan handler:event 'App\Handlers\Events\LaradropFileWasUploaded' --event='Jasekz\Laradrop\Events\FileWasUploaded'` isnt working for some reason. Am on 5.3

**Comment by jasekz** [comment]
I'm testing this on 5.3 now and expect to have a solution for you shortly, but let me know if you find something before then.  Thanks for taking the time to work through this.

**Comment by jasekz** [comment]
Try this:
1. Delete the ` /public/vendor/jasekz` directory.
2. Re-install the latest version of laradrop.
3. Re-run `artisan vendor:publish`

Let me know how it goes.

**Comment by devingray** [comment]
Hi Zig. It is wierd, am still not hitting my controller. I think the solution to my problem will be to create a trait for the images, then on successfull upload, send the image ID to my trait and just run a raw DB query to update this field in the Database, then return back the way you have it working. Am trying it out now. Such a rad package :D

**Comment by devingray** [comment]
Okay :D This is my final answer, yes I am sure, Lock it in! ;) Found best solution here https://laracasts.com/discuss/channels/general-discussion/l5-service-provider-for-sharing-view-variables

**Comment by jasekz** [comment]
Ok, thanks, Dev.  Yeah, that's strange because I can get this to work as expected on my end.  I'll go ahead and close this out, but one more thing you may want to verify in your browser's network inspector, is that  when you do an upload, the ajax call actually goes to /mediaStore, and not /laradrop.  If it doesn't, it's most likely that you're running off of the old `laradrop.js` file.

**Comment by devingray** [comment]
Just a last bit of info regarding this. I was an idiot and overlooked the easiest option. 

onSuccessCallback(){
do an ajax request to my controller 
}

**Comment by jasekz** [comment]
:+1:
