### ISSUE TITLE
Compatibility with Laravel 5.3

### ISSUE THREAD

**Issue by kotarCreative** [jasekz/laradrop#14]
Is laradrop compatible with 5.3 or is it only tested on the 5.2 file structure?

**Comment by devingray** [comment]
Hi there, I am running it on 5.3, you need to change the service provider and it works https://github.com/jasekz/laradrop/issues/11

**Comment by jasekz** [comment]
Thanks, Devin.  If you're doing a fresh install of 5.3, it should also work out of the box.

EDIT:  It take that back, Devin is correct.  I'm working on a patch for this right now.

**Comment by kotarCreative** [comment]
Oh ok thanks. Are you going to push this to the main package?

**Comment by jasekz** [comment]
Yes.

**Comment by jasekz** [comment]
Hey David,
Laravel 5.3 is now supported in the latest release, 1.0.2.  Please let me know if you do encounter any issues.

Thanks,
Zig
