### ISSUE TITLE
would you consider using this vue-dropzone instead?

### ISSUE THREAD

**Issue by vesper8** [jasekz/laradrop#17]
I think this would go well with the spirit of using vuejs with laravel

https://github.com/rowanwins/vue-dropzone

And also Laravel 5.4 just came out. I don't know if there's any incompatibility with this plugin.. probably not

Love your work! Thanks!

**Comment by jasekz** [comment]
Thanks, @vesper8 .  Yeah, it looks great.  I'd definitely be interested in using it.
