### ISSUE TITLE
http://localhost/laradrop/containers NOT FOUND

### ISSUE THREAD

**Issue by minhliem86** [jasekz/laradrop#23]
Hi Jasekz,

Thank for your package. It's interesting me. But I have a problem when install it into my project. When I install and run my url it show alert "Not Found". I followed all steps to install. Thank Jasekz again. Regards,

**Comment by jasekz** [comment]
@minhliem86 Is your app located in a subdirectory, i.e http://localhost/myapp?  Also, please take a look at https://github.com/jasekz/laradrop/issues/16 to see if anything there may apply to your situation.

**Comment by minhliem86** [comment]
Thanks jasekz so much.

**Comment by jasekz** [comment]
@minhliem86 I'm going to close this out.  Feel free to reopen if the issue is not resolved.
