### ISSUE TITLE
artisan vendor:publish do not publish related files

### ISSUE THREAD

**Issue by saeedmie85** [jasekz/laradrop#24]
In boot method on LaradropServiceProvider.php there is some file address than a need to publish.
when I use 'artisan vendor:publish' these files do not publish on a related directory.
please help me to fix this problem.

**Comment by jasekz** [comment]
@saeedmie85 Can you post the error you're seeing?

**Comment by saeedmie85** [comment]
@jasekz I don't see any error when running the  'artisan vendor:publish'. I see following comment after running that command.
Warning: Module 'openssl' already loaded in Unknown on line 0
Copied Directory [\vendor\laravel\framework\src\Illuminate\Notifications\resources\views] To [\resources\views\vendor\notifications]
Copied Directory [\vendor\laravel\framework\src\Illuminate\Pagination\resources\views] To [\resources\views\vendor\pagination]
Copied Directory [\vendor\arcanedev\log-viewer\resources\views] To [\resources\views\vendor\log-viewer]
Copied Directory [\vendor\arcanedev\log-viewer\resources\lang] To [\resources\lang\vendor\log-viewer]
Copied Directory [\vendor\yajra\laravel-datatables-oracle\src\resources\views] To [\resources\views\vendor\datatables]
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0
Publishing complete for tag []!


There is not any file from jasekz/laradrop package. I except the "laradrop.php" copy to "config" folder
and "migrations" directory copy to the "database" directory and "/resources/assets" folders copy to 'vendor/jasekz/laradrop'
but this will not happen.

**Comment by jasekz** [comment]
Can you verify that:
1. vendor/jasekz/laradrop/src/Jasekz/Laradrop exists and contains all the necessary file/directories in your app's vendor dir
2. you have added 'Jasekz\Laradrop\LaradropServiceProvider' to your config/app.php providers

**Comment by saeedmie85** [comment]
@jasekz yes 
C:/xampp/htdocs/laravel/laravel/myapp/vendor/jasekz/laradrop/src/Jasekz/Laradrop

is exists and contains all the necessary file/directories in my app's vendor dir
And I added  'Jasekz\Laradrop\LaradropServiceProvider' to my config/app.php providers
but my issue still exists. Perhaps it is necessary that noticed I use Laravel 5.3

**Comment by jasekz** [comment]
Your Laravel version shouldn't be the issue, provided it it's L5.  I can not recreate the problem, but my suggestion would be to do a fresh Laravel install and try with that.  Sorry, I'm not able to debug this any further without working in your environment.

**Comment by saeedmie85** [comment]
Thank you very much, I will try to fix that.

**Comment by saeedmie85** [comment]
I fixed the issue.
first, i run this command.
   php artisan config:clear
then retry
php artisan vendor:publish

**Comment by jasekz** [comment]
Awesome.
