### ISSUE TITLE
costumize index method

### ISSUE THREAD

**Issue by saeedmie85** [jasekz/laradrop#25]
hello 
I save my photos in a folder like this
 ` $disk->put(
                    'cofeeshops/' . $coffeeshop->id . '/main/' . $movedFileName,
                    fopen($tmpStorage . '/' . $movedFileName, 'r+'));`
and save the path of photos in the photos table that I created in db like this
`

                $photo                 = new Photo();

                $photo->path           = $disk->url('cofeeshops/' . $coffeeshop->id . '/main/' . $movedFileName);

                $photo->directory      = $disk->url('cofeeshops/' . $coffeeshop->id . '/main');

                $photo->imageable_id   = $coffeeshop->id;

                $photo->imageable_type = 'coffeeshop';

                $photo->save();`

now, how can I develop my own index method?

**Comment by jasekz** [comment]
hey @saeedmie85 , that looks like it's outside the scope of this package.  Without seeing the code, it's difficult for me to understand what you have and what you're trying to accomplish.

**Comment by saeedmie85** [comment]
thanx for your answering
my controller for store and index photo is:
`   class PhotoContoroller extends LaradropController
    {

        public function storeCoffeeshopPhotos(Coffeeshop $coffeeshop)
        {

            try
                {

                if (!Request::hasFile('file'))
                    {
                    throw new Exception(trans('err.fileNotProvided'));
                    }

                if (!Request::file('file')->isValid())
                    {
                    throw new Exception(trans('err.invalidFile'));
                    }

                /*
                 * move file to temp location
                 */
                $fileExt  = Input::file('file')->getClientOriginalExtension();
                $fileName = str_replace('.' . $fileExt, '', Input::file('file')->getClientOriginalName()) . '-' .
                            date('Ymdhis');
                // $mimeType      = Request::file('file')->getMimeType();
                $tmpStorage    = storage_path();
                $movedFileName = $fileName . '.' . $fileExt;
                $fileSize      = Input::file('file')->getSize();

                if ($fileSize > ((int)config('laradrop.max_upload_size') * 1000000))
                    {
                    throw new Exception(trans('err.invalidFileSize'));
                    }

                Request::file('file')->move($tmpStorage, $movedFileName);

                $disk = Storage::disk(config('laradrop.disk'));

                /*
                 * move uploaded file to final location
                 */
                $disk->put(
                    'cofeeshops/' . $coffeeshop->id . '/main/' . $movedFileName,
                    fopen($tmpStorage . '/' . $movedFileName, 'r+'));
                File::delete($tmpStorage . '/' . $movedFileName);

                /*
                 * save in db
                 */

                $photo                 = new Photo();
                $photo->path           = $disk->url('cofeeshops/' . $coffeeshop->id . '/main/' . $movedFileName);
                $photo->directory      = $disk->url('cofeeshops/' . $coffeeshop->id . '/main');
                $photo->imageable_id   = $coffeeshop->id;
                $photo->imageable_type = 'coffeeshop';

                $photo->save();

                /*
                 * fire 'file uploaded' event
                 */
                event(
                    new FileWasUploaded(
                        [
                            'file'     => $photo,
                            'postData' => Input::all(),
                        ]));

                return $photo;

                } catch (Exception $e)
                {

                // delete the file(s)
                if (isset($disk) && $disk)
                    {
                    $disk->delete($movedFileName);
                    $disk->delete('_thumb_' . $movedFileName);
                    }

                return $this->handleError($e);
                }
        }

        public function indexCoffeeshopPhotos(Coffeeshop $coffeeshop)
        {
            try
                {
                $folderId = Input::get('pid');

                // $d=$coffeeshop->photos()->find(1)->directory;
                $files = $this->file->get($folderId);

                return response()->json(
                    [
                        'status' => 'success',
                        'data'   => $files,
                    ]);
                } catch (Exception $e)
                {
                return $this->handleError($e);
                }
        }
    }
`
the storeCoffeeshopPhotos() function is work but I dont know how costumise the  indexCoffeeshopPhotos(Coffeeshop $coffeeshop) function

**Comment by saeedmie85** [comment]
what is this the
            Input::get('pid')
and how change the 'pid'

**Comment by jasekz** [comment]
Since you're using your own custom table instead of the `laradrop_files` table, you're going to need to modify the model as well and ensure that all the necessary fields are there to track the directory structure.  The pid stands for `parent_id` and refers to the parent directory (`laradrop_files`.`parent_id`).  

Overall, it appears that you want to override the files table with additional fields specific to your business logic.  Although you can do it the way you are, I would advise extending the table instead.

**Comment by jasekz** [comment]
I'm going to close this out, but feel to re-open if needed.
