### ISSUE TITLE
Is there a way to limit extensions?

### ISSUE THREAD

**Issue by LTroya** [jasekz/laradrop#27]
Is currently a way to limit the file extensions that the user is able to upload?

Or maybe,

I can validate the extension on `onInsertCallback` but I don't know how to remove from the list of files to the upload.

If you could give me some hints I would appreciate it. Thanks in advance

**Comment by jasekz** [comment]
Hi @LTroya , 
Currently there is no way to whitelist/blacklist file types.  I think the best way to accomplish this would be to create your own controller and extend LaradropController.  You could then override  `store()` to handle your validation logic.  For example:

```
class YourController extends LaradropController {
  
  public function store() {

    try {
      if(Input::file('file')->getClientOriginalExtension() != 'pdf'){
        throw new Exception('We only accept pdf files');
      }

      parent::store();
    }

    catch (Exception $e) {
      return $this->handleError($e);
    }
  }
}
```
