### ISSUE TITLE
How do I show the actual progress of the file upload?

### ISSUE THREAD

**Issue by Kendysond** [jasekz/laradrop#28]
Hello, 

On the live demo, the upload progress bar seems to be consistent with the upload progress of the file, however, on my setup, the progress bar extends to the end immediately the "start upload" button is clicked. 

I followed the instructions on the repo. 

Please is there any extra settings to be made to show the actual progress of the file upload?

**Comment by jasekz** [comment]
HI @Kendysond ,
The progress bar is handled by Dropzone.js and there are no settings for it.  If there is a significant delay between the time that the progress bar 'completes' and the file show up in the browser, it is likely that your server is taking a longer time to process the file.  The progress bar only shows the upload, but does not account for the time taken to generate the thumbnail, re-size the image, and move it to the final location.  Hope that answers your question.

**Comment by Kendysond** [comment]
Apologies for the tardy response. 
That helps! 

Thank you @jasekz .
