### ISSUE TITLE
Folder image location.

### ISSUE THREAD

**Issue by FooleanBool** [jasekz/laradrop#29]
EDIT: Found the answer in the laradrop.js file:

`folderImage = options.folderImage ? options.folderImage : '
/vendor/jasekz/laradrop/img/genericThumbs/folder.png',`

Hey :)
I'm integrating this package into a Laravel 5.4 application - I've got everything configured and working well, other than the folder image. 
No matter what I have tried, I cannot change the location of this image from the vendor folder which won't load into the browser even though I can see it exists in the vendor folder.

`<img src="/vendor/jasekz/laradrop/img/genericThumbs/folder.png" alt="09.08.2017 - 13:33:57">`
This always returns not found. I've scoured the source files of the package and cannot find a place to change this path to a publicly accessible one (the app I am extending has a non-standard assets path above the project folder).

Could you point me to the correct place to change this path to reflect my installation config?
I have the file ready in a publicly accessible folder:
http://mydom.com/assets/vendor/jasekz/laradrop/img/genericThumbs/folder.png
So I would just need to prepend 'assets/' to the image src string.
Thanks :)

**Comment by jasekz** [comment]
Hey @zigstum ,
You should be able to accomplish this in a couple of ways:
- set the 'default_thumbnail_url' in `https://github.com/jasekz/laradrop/blob/dev/src/Jasekz/Laradrop/config/config.php` (the actual file should be in your app's config dir)
- set the 'folderImage' when instantiating the laradrop js object: 
`jQuery('.laradrop').laradrop({folderImage:"/your/path/to/img.jpg");`

Let me know if that works for you.

Thanks

**Comment by FooleanBool** [comment]
@jasekz  
I hadn't noticed the default thumbnail option in the docs, but finding this JS made me realise it was an option.
Thanks for the package - I am using it as a gallery manager for an uploaded product - it was just a multi-choice browse button originally - this will be a good upgrade.
Cheers :)

**Comment by jasekz** [comment]
Awesome, thanks, @zigstum.  Yeah, the js options aren't documented, but you can see what's supported in https://github.com/jasekz/laradrop/blob/dev/src/Jasekz/Laradrop/resources/assets/js/laradrop.js.
