### ISSUE TITLE
handlers

### ISSUE THREAD

**Issue by bikedel** [jasekz/laradrop#3]
hello I am trying to implement my own handler

<div class="laradrop" laradrop-csrf-token="{{ csrf_token() }}"  laradrop-upload-handler="{{ route('uploaded') }}"> </div>

It does not appear to do anything

I have tested the route independently and it works
the route is in my route file not laradrops - is that correct?

**Comment by jasekz** [comment]
If you mean a route/controller override, then you can just create your own controller, a route to point to it, and extend the Laradrop controller.  If you mean an 'event' handler, then you just need to register a handler to listen for the Lardrop events and handle them accordingly.

Please check the Laradrop controller and routes for examples.

**Comment by bikedel** [comment]
that is what I did - guess I need to understand more

**Comment by jasekz** [comment]
Is there something specific you are trying to accomplish?

**Comment by bikedel** [comment]
drag and drop file manager
email templater

learning as I go....
