### ISSUE TITLE
Display Folder Images on Page Load

### ISSUE THREAD

**Issue by FooleanBool** [jasekz/laradrop#31]
Hey Zig, Zig here :)

Could you advise me on how to have a specific folder loaded into the containers. 
I've looked through laradrop.js but cannot find my way in there so well.
Also, browser inspectors show no event lisetner bound to the folder image (the image you click to show the images inside.)

I'd like to be able to offer a link so that the containers load a specific folder - meaning the images inside the folder, as if the folder had been clicked to view the contents. 

I apologise if this is a trivial matter, I just figured you are helpfull and are in the best poition to give advice on this.

Thanks :)

**Comment by FooleanBool** [comment]
It was so simple :)
Just pass 'fileSrc' in with the options.
I love this package :1st_place_medal:

**Comment by jasekz** [comment]
Awesome, Zig.  Thanks so much and feel free to reach out with any questions, comments or PRs.
