### ISSUE TITLE
its not publishing the files needed 

### ISSUE THREAD

**Issue by jihadismail8** [jasekz/laradrop#32]
php artisan  publishing is not pulling the files , i tried to clear configs , to clear chache , to  autodump , not working at all.  please fix this

**Comment by jasekz** [comment]
Can you verify that your 'config' and 'public' directories are writable?  Also, are you getting any errors when you try to publish?

**Comment by jihadismail8** [comment]
yea , they are writable ( 100% sure )  no i am not getting any error . i tried everything  any ideas ?? please do not close this issue , because this is not the first time it happens , and  am not the first one who happened to , so lets try to fix it please

**Comment by jasekz** [comment]
Which Laravel version are you using?

**Comment by jihadismail8** [comment]
5.5  , i tried 5.3 also 
add on me on facebook  if you , and we can fix then post the fix here :)  jihad ismail ( no profile pic  from russia)

**Comment by jasekz** [comment]
Can you set your 'public' and 'config' directories to 777 and try?  I just want to rule out permissions issues.  I can not reproduce this error, so I'll need your feedback.  Also, can you provide your env specifics? (os, server, php version, etc)

**Comment by jihadismail8** [comment]
i did chmod 777 again , i tried another filemanager package ( and the chmod 777 works 100 % ) ,  i am using  windows 10 with linux subsystem , php 7  , and server is  the embaded php artisan serve

**Comment by jihadismail8** [comment]
if you have already , i builded package on laravel 5.5 , could you please  share it ?

**Comment by jasekz** [comment]
I'm sending you the files that get published, but if you find a solution to this problem, please send me a pull request and I'll be happy to commit.

[laradrop.zip](https://github.com/jasekz/laradrop/files/1681916/laradrop.zip)

**Comment by jihadismail8** [comment]
and where is the views ?

**Comment by jasekz** [comment]
Views are in the package code.
