### ISSUE TITLE
laravel won't pull files from files from vendor folder

### ISSUE THREAD

**Issue by marko-mlinarevic** [jasekz/laradrop#5]
as the title say laravel won't  pull files I'm calling from vendor

for example

```


<script src="vendor/jasekz/laradrop/js/enyo.dropzone.js"></script>
<script src="vendor/jasekz/laradrop/js/laradrop.js"></script>

```

It says it cannot find them

EDIT: Found the problem but cannot find solution.  artisan vendor:publish does not copy the public file to assets

**Comment by jasekz** [comment]
Hi Marko,
Can you verify that your assets directory has the proper permissions for Laravel artisan to write the files to?

**Comment by jihadismail8** [comment]
its still not working ,  the vendor:publish is not pulling the files
